// Build the test SaaS MSA — vendor's paper, ~6000 words, 10 sections.
// Realistic-feeling provisions chosen to surface specific reasoning tests:
//   • Net-60 / 1.5%/mo late fee (vs. buyer Net-30 playbook)
//   • LoL = 12 mo fees with carve-outs (vs. buyer 1x fees)
//   • Vendor IP indemnity capped at LoL; NO customer indemnity (vs. buyer mutual)
//   • Vendor retains platform IP; customer owns data; outputs unaddressed
//   • Auto-renewal 1-year evergreen, 60-day cancellation notice
//   • Asymmetric cure: vendor 30 days, customer 60 days
//   • Mutual confidentiality with 3-year tail
//   • SOC 2 Type II, breach notification within 72 hours
//   • Subcontracting allowed without notice (vs. buyer notice + approval)
//   • Insurance $2M GL, $5M E&O
//   • DE governing law; AAA arbitration in vendor's home state (CA)
//   • Standard force majeure
//   • Notices: written, email permitted

import fs from 'node:fs';
import path from 'node:path';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';

const OUT = path.resolve('tools/contract-grader/test_contracts/msa_reasoning_test.docx');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
const heading = (text, level = HeadingLevel.HEADING_1) =>
  new Paragraph({ heading: level, children: [new TextRun({ text, bold: true })] });

const body = (text) =>
  new Paragraph({ children: [new TextRun(text)], spacing: { after: 200 } });

const section = (label, text) =>
  new Paragraph({
    children: [new TextRun({ text: label, bold: true }), new TextRun({ text: ' ' + text })],
    spacing: { after: 200 },
  });

// ---------------------------------------------------------------------------
// Document content
// ---------------------------------------------------------------------------
const children = [];

// Title
children.push(new Paragraph({
  alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: 'MASTER SUBSCRIPTION AGREEMENT', bold: true, size: 32 })],
  spacing: { after: 300 },
}));

children.push(new Paragraph({
  alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: 'Lattice Telemetry, Inc.', italics: true })],
  spacing: { after: 400 },
}));

children.push(body(
  'This Master Subscription Agreement (this "Agreement") is entered into as of the Effective Date set forth in the applicable Order Form by and between Lattice Telemetry, Inc., a Delaware corporation having its principal place of business at 401 California Street, Suite 1200, San Francisco, California 94104 ("Lattice"), and the customer identified in the applicable Order Form ("Customer"). Each of Lattice and Customer is sometimes referred to herein as a "Party" and collectively as the "Parties." This Agreement governs the provision and use of the Subscription Services (as defined below) and any related Professional Services (as defined below).'
));

// =========================================================================
// 1. DEFINITIONS
// =========================================================================
children.push(heading('1. DEFINITIONS'));
children.push(body('Capitalized terms used in this Agreement shall have the meanings set forth below or as otherwise defined herein:'));

const defs = [
  ['"Affiliate"', 'means, with respect to a Party, any entity that directly or indirectly controls, is controlled by, or is under common control with such Party, where "control" means ownership of more than fifty percent (50%) of the outstanding voting securities or equivalent.'],
  ['"Authorized User"', 'means an employee or contractor of Customer or its Affiliates who is authorized by Customer to access and use the Subscription Services and to whom Customer has provided unique login credentials.'],
  ['"Confidential Information"', 'has the meaning set forth in Section 7.1.'],
  ['"Customer Data"', 'means any data, information, or content uploaded, transmitted, or otherwise made available by Customer or its Authorized Users to or through the Subscription Services, but excludes Usage Data and any data generated by Lattice in the course of operating, maintaining, monitoring, or improving the Subscription Services.'],
  ['"Documentation"', 'means the user guides, administrative manuals, online help files, and other written materials Lattice provides or makes generally available with the Subscription Services, as updated by Lattice from time to time.'],
  ['"Effective Date"', 'means the date specified as such on the applicable Order Form, or, if no such date is specified, the date of the Order Form.'],
  ['"Fees"', 'means the fees specified in an Order Form for the Subscription Services and Professional Services.'],
  ['"Initial Term"', 'means the initial subscription term specified on the applicable Order Form.'],
  ['"Order Form"', 'means a written ordering document executed by both Parties referencing this Agreement and specifying the Subscription Services to be provided, the applicable Fees, the Initial Term, and other commercial terms.'],
  ['"Professional Services"', 'means the implementation, configuration, training, and other consulting services that Lattice provides to Customer pursuant to a Statement of Work or as specified in an Order Form.'],
  ['"Renewal Term"', 'has the meaning set forth in Section 4.2.'],
  ['"Statement of Work" or "SOW"', 'means a written document executed by both Parties referencing this Agreement that describes the scope, deliverables, fees, and timeline for Professional Services.'],
  ['"Subscription Services"', 'means the cloud-hosted software-as-a-service platform and related functionality offered by Lattice and identified in the applicable Order Form, together with the Documentation.'],
  ['"Subscription Term"', 'means the Initial Term together with any subsequent Renewal Terms.'],
  ['"Usage Data"', 'means data and information that Lattice collects regarding the operation, performance, and use of the Subscription Services, including without limitation log data, performance metrics, telemetry, and analytics, but excluding any Customer Data.'],
];
defs.forEach(([term, def]) => children.push(section(term, def)));

// =========================================================================
// 2. SUBSCRIPTION SERVICES
// =========================================================================
children.push(heading('2. SUBSCRIPTION SERVICES'));

children.push(section('2.1 Grant.',
  'Subject to the terms and conditions of this Agreement and timely payment of the Fees, Lattice grants Customer a non-exclusive, non-transferable, non-sublicensable right during the Subscription Term to access and use the Subscription Services solely for Customer\'s internal business purposes and only in accordance with the Documentation and any usage limits set forth in the applicable Order Form. Customer may permit Authorized Users to access and use the Subscription Services on Customer\'s behalf, provided that Customer remains responsible for the acts and omissions of its Authorized Users.'
));

children.push(section('2.2 Restrictions.',
  'Customer shall not, and shall not permit any Authorized User or third party to: (a) reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code, object code, or underlying structure or algorithms of the Subscription Services; (b) modify, translate, or create derivative works based on the Subscription Services; (c) rent, lease, distribute, sell, resell, sublicense, or otherwise commercially exploit the Subscription Services; (d) circumvent any access or use restrictions or security measures; (e) use the Subscription Services to develop a competing product or service, or for benchmarking or competitive analysis; (f) introduce any malicious code or attempt to interfere with the integrity or operation of the Subscription Services; or (g) use the Subscription Services in violation of applicable law or third-party rights.'
));

children.push(section('2.3 Service Levels.',
  'Lattice will provide the Subscription Services in substantial conformance with the service-level commitments set forth in the Service Level Schedule attached as Exhibit A. Lattice\'s sole obligations and Customer\'s sole and exclusive remedies for failures to meet such service-level commitments are the service credits described in Exhibit A. Service credits do not constitute liquidated damages or limit Lattice\'s rights under this Agreement, and Customer\'s sole remedy in the event of repeated failures shall be the right to terminate the affected Subscription Service in accordance with Section 4.3.'
));

children.push(section('2.4 Modifications.',
  'Lattice may, in its sole discretion, modify, update, or enhance the Subscription Services from time to time, provided that no such modification will materially diminish the core functionality of the Subscription Services described in the applicable Order Form during the then-current Subscription Term.'
));

children.push(section('2.5 Professional Services.',
  'If Customer engages Lattice to provide Professional Services, such services will be performed pursuant to a mutually agreed Statement of Work. Each SOW will identify the scope of work, deliverables (if any), fees, milestones, and any acceptance criteria. Unless otherwise specified in an SOW, Professional Services are provided on a time-and-materials basis. Lattice retains all right, title, and interest in any methodology, know-how, tools, and pre-existing materials used in connection with Professional Services.'
));

// =========================================================================
// 3. FEES AND PAYMENT
// =========================================================================
children.push(heading('3. FEES AND PAYMENT'));

children.push(section('3.1 Fees.',
  'Customer will pay Lattice the Fees specified in each Order Form. Except as expressly provided in this Agreement, all Fees are non-refundable and non-cancelable. Fees do not include any taxes, levies, duties, or similar governmental assessments of any nature, including value-added, sales, use, or withholding taxes ("Taxes"), and Customer is responsible for payment of all Taxes associated with its purchases hereunder, excluding only Taxes based on Lattice\'s net income.'
));

children.push(section('3.2 Invoicing and Payment.',
  'Unless otherwise specified in an Order Form, Lattice will invoice Customer annually in advance for the Subscription Services. All invoices are payable in U.S. dollars and are due net sixty (60) days from the date of invoice. Customer is responsible for providing complete and accurate billing and contact information to Lattice and notifying Lattice of any changes to such information.'
));

children.push(section('3.3 Late Payments.',
  'Any amounts not paid when due will accrue interest at the rate of one and one-half percent (1.5%) per month, or the maximum rate permitted by applicable law, whichever is lower, calculated from the date such payment was due until the date paid. Customer will reimburse Lattice for all reasonable costs of collection (including attorneys\' fees) incurred in collecting any past-due amounts.'
));

children.push(section('3.4 Suspension for Non-Payment.',
  'If any amount owing by Customer is more than thirty (30) days overdue, Lattice may, without limiting its other rights and remedies, suspend Customer\'s access to the Subscription Services until such amounts are paid in full. Lattice will provide Customer with at least ten (10) days\' prior notice that Customer\'s account is overdue before suspending the Subscription Services.'
));

children.push(section('3.5 Fee Increases.',
  'Lattice may increase the Fees applicable to a Renewal Term by providing Customer with written notice (which may be by email) at least sixty (60) days prior to the end of the then-current Subscription Term. Any such increase will take effect at the start of the next Renewal Term.'
));

// =========================================================================
// 4. TERM AND TERMINATION
// =========================================================================
children.push(heading('4. TERM AND TERMINATION'));

children.push(section('4.1 Term of Agreement.',
  'This Agreement commences on the Effective Date of the first Order Form and continues until all Order Forms have expired or been terminated and all amounts due hereunder have been paid in full.'
));

children.push(section('4.2 Subscription Term; Renewal.',
  'Each Order Form sets forth its own Initial Term. Unless otherwise specified in an Order Form, upon expiration of the Initial Term, the Subscription Services will automatically renew for successive one-year periods (each, a "Renewal Term") unless either Party provides written notice of non-renewal to the other Party at least sixty (60) days prior to the end of the then-current Subscription Term. The Initial Term and any Renewal Terms together constitute the Subscription Term.'
));

children.push(section('4.3 Termination for Cause.',
  'Lattice may terminate this Agreement or any Order Form upon written notice to Customer if Customer materially breaches this Agreement and fails to cure such breach within thirty (30) days after receipt of written notice describing the breach in reasonable detail. Customer may terminate this Agreement or any Order Form upon written notice to Lattice if Lattice materially breaches this Agreement and fails to cure such breach within sixty (60) days after receipt of written notice describing the breach in reasonable detail. Either Party may terminate this Agreement immediately upon written notice if the other Party becomes insolvent, makes an assignment for the benefit of creditors, or files or has filed against it a petition in bankruptcy that is not dismissed within sixty (60) days.'
));

children.push(section('4.4 Effect of Termination.',
  'Upon any expiration or termination of this Agreement: (a) Customer\'s right to access and use the Subscription Services will immediately terminate; (b) Customer will pay Lattice all Fees due and payable as of the effective date of termination, and, if Customer terminates this Agreement other than for Lattice\'s uncured material breach pursuant to Section 4.3, Customer shall pay all Fees that would have been payable for the remainder of the then-current Subscription Term; (c) for thirty (30) days following termination, Lattice will, upon Customer\'s written request and at Customer\'s expense, make Customer Data available for download in a commercially reasonable format. After such thirty-day period, Lattice may delete or destroy Customer Data in its possession or control.'
));

children.push(section('4.5 Survival.',
  'The provisions of Sections 1, 3 (with respect to amounts accrued prior to termination), 4.4, 4.5, 6, 7, 8, 9, and 10 will survive any expiration or termination of this Agreement.'
));

// =========================================================================
// 5. CUSTOMER DATA; SECURITY; PRIVACY
// =========================================================================
children.push(heading('5. CUSTOMER DATA; DATA SECURITY; PRIVACY'));

children.push(section('5.1 Customer Data.',
  'As between the Parties, Customer retains all right, title, and interest in and to Customer Data. Customer is solely responsible for the accuracy, quality, integrity, legality, and reliability of Customer Data and the means by which it acquires Customer Data. Customer hereby grants Lattice a non-exclusive, worldwide, royalty-free license to host, copy, transmit, display, and otherwise process Customer Data solely as necessary for Lattice to provide and support the Subscription Services in accordance with this Agreement.'
));

children.push(section('5.2 Information Security Program.',
  'Lattice will implement and maintain a written information security program that includes administrative, technical, and physical safeguards designed to protect the security, confidentiality, and integrity of Customer Data. Lattice will maintain a SOC 2 Type II report covering the security trust principle and will provide a copy of its most recent report to Customer upon written request and Customer\'s execution of a non-disclosure agreement covering such report.'
));

children.push(section('5.3 Security Incidents.',
  'Lattice will notify Customer in writing without undue delay, and in any event within seventy-two (72) hours, after becoming aware of any unauthorized access to or acquisition of Customer Data ("Security Incident"). Such notification will include a description of the nature of the Security Incident, the categories and approximate number of records affected (to the extent then known), the measures Lattice has taken or proposes to take in response, and the contact details of an appropriate point of contact at Lattice for further information. Lattice will reasonably cooperate with Customer\'s investigation of any Security Incident.'
));

children.push(section('5.4 Privacy and Data Protection.',
  'To the extent that Customer Data includes personal data subject to applicable data protection laws, the Parties will execute Lattice\'s standard Data Processing Addendum, which is incorporated by reference. The Data Processing Addendum sets forth the Parties\' respective obligations with respect to the processing of personal data and shall control over any conflicting provisions of this Agreement with respect to such processing.'
));

children.push(section('5.5 Usage Data.',
  'Customer acknowledges that Lattice collects and uses Usage Data for purposes of operating, supporting, securing, and improving the Subscription Services and developing new products and services. Lattice may aggregate and anonymize Usage Data and use such aggregated and anonymized data for any lawful business purpose, provided that such aggregated and anonymized data does not identify Customer or any Authorized User.'
));

// =========================================================================
// 6. INTELLECTUAL PROPERTY
// =========================================================================
children.push(heading('6. INTELLECTUAL PROPERTY'));

children.push(section('6.1 Lattice IP.',
  'Lattice and its licensors own and shall retain all right, title, and interest in and to the Subscription Services, the Documentation, and any improvements, enhancements, derivative works, modifications, or other developments to or based on any of the foregoing, including all intellectual property rights therein. Except for the express rights granted to Customer in this Agreement, Lattice reserves all rights, titles, and interests in and to the Subscription Services, Documentation, and the foregoing materials. No licenses or rights are granted by implication, estoppel, or otherwise.'
));

children.push(section('6.2 Customer Data.',
  'As between the Parties, Customer retains all right, title, and interest in and to Customer Data, subject to the license granted to Lattice in Section 5.1.'
));

children.push(section('6.3 Feedback.',
  'If Customer or its Authorized Users provide Lattice with any suggestions, recommendations, ideas, or feedback regarding the Subscription Services or the business of Lattice ("Feedback"), Customer hereby grants Lattice a non-exclusive, perpetual, irrevocable, worldwide, royalty-free, transferable, sublicensable right and license to use, copy, modify, distribute, and otherwise exploit such Feedback for any purpose, without any obligation or compensation to Customer.'
));

// =========================================================================
// 7. CONFIDENTIALITY
// =========================================================================
children.push(heading('7. CONFIDENTIALITY'));

children.push(section('7.1 Definition.',
  '"Confidential Information" means any non-public information disclosed by one Party (the "Disclosing Party") to the other Party (the "Receiving Party"), whether orally, in writing, or in any other form, that is designated as confidential or that, given the nature of the information and the circumstances of disclosure, would reasonably be understood to be confidential. Without limiting the foregoing, the terms and conditions of this Agreement and each Order Form, the Subscription Services, and Lattice\'s technical, security, and audit information shall be considered Lattice\'s Confidential Information; and Customer Data shall be considered Customer\'s Confidential Information.'
));

children.push(section('7.2 Obligations.',
  'The Receiving Party agrees: (a) to use Confidential Information of the Disclosing Party only for purposes of performing its obligations or exercising its rights under this Agreement; (b) to protect Confidential Information of the Disclosing Party using at least the same degree of care it uses to protect its own confidential information of similar nature, but in no event less than a reasonable degree of care; and (c) to limit access to Confidential Information of the Disclosing Party to those employees, contractors, and agents who have a need to know such information and who are bound by confidentiality obligations no less protective than those set forth herein.'
));

children.push(section('7.3 Exceptions.',
  'The obligations set forth in Section 7.2 do not apply to information that the Receiving Party can demonstrate: (a) was already known to it without restriction at the time of disclosure; (b) is or becomes publicly available through no breach of this Agreement by the Receiving Party; (c) is independently developed by the Receiving Party without use of or reference to the Disclosing Party\'s Confidential Information; or (d) is rightfully received from a third party without breach of any confidentiality obligation. The Receiving Party may disclose Confidential Information to the extent required by law or court order, provided that the Receiving Party gives the Disclosing Party reasonable advance notice (where legally permitted) and reasonable cooperation in seeking a protective order.'
));

children.push(section('7.4 Term of Confidentiality.',
  'The obligations of confidentiality set forth in this Section 7 will continue during the Subscription Term and for a period of three (3) years thereafter, except that with respect to trade secrets such obligations will continue for as long as the information qualifies as a trade secret under applicable law.'
));

// =========================================================================
// 8. WARRANTIES; INDEMNIFICATION; LIMITATION OF LIABILITY
// =========================================================================
children.push(heading('8. WARRANTIES; INDEMNIFICATION; LIMITATION OF LIABILITY'));

children.push(section('8.1 Lattice Warranties.',
  'Lattice represents and warrants that: (a) it has full power and authority to enter into and perform this Agreement; (b) the Subscription Services will perform substantially in accordance with the Documentation under normal use during the Subscription Term; and (c) it will perform Professional Services in a workmanlike manner and substantially in accordance with the applicable SOW. Customer\'s sole and exclusive remedy and Lattice\'s entire liability for any breach of the warranty in clause (b) is, at Lattice\'s option and expense, to (i) modify the Subscription Services to make them conform to the warranty, (ii) provide a workaround, or (iii) terminate the affected Subscription Services and refund any prepaid Fees for the period after termination.'
));

children.push(section('8.2 Disclaimer.',
  'EXCEPT AS EXPRESSLY SET FORTH IN SECTION 8.1, THE SUBSCRIPTION SERVICES, DOCUMENTATION, AND PROFESSIONAL SERVICES ARE PROVIDED "AS IS." LATTICE DISCLAIMS ALL OTHER WARRANTIES, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, AND ANY WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE. LATTICE DOES NOT WARRANT THAT THE SUBSCRIPTION SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS, OR THAT CUSTOMER DATA WILL BE SECURE OR NOT OTHERWISE LOST OR DAMAGED.'
));

children.push(section('8.3 Lattice IP Indemnity.',
  'Lattice will defend Customer against any claim, suit, or proceeding brought by a third party alleging that Customer\'s use of the Subscription Services in accordance with this Agreement directly infringes such third party\'s patent, copyright, trademark, or trade secret rights (an "Infringement Claim"), and will indemnify Customer for any damages finally awarded against Customer (or amounts paid in settlement approved by Lattice) in connection with any Infringement Claim. Lattice\'s obligations under this Section 8.3 do not apply to any Infringement Claim arising from: (a) Customer Data; (b) modification of the Subscription Services by anyone other than Lattice; (c) use of the Subscription Services in combination with any product, service, or data not provided by Lattice; or (d) use of the Subscription Services other than in accordance with this Agreement and the Documentation. If the Subscription Services become, or in Lattice\'s opinion are likely to become, the subject of an Infringement Claim, Lattice may, at its option and expense, (i) procure for Customer the right to continue using the Subscription Services, (ii) modify the Subscription Services so they no longer infringe, or (iii) terminate the affected Subscription Services and refund any prepaid Fees for the period after termination. THIS SECTION 8.3 SETS FORTH LATTICE\'S SOLE AND EXCLUSIVE LIABILITY, AND CUSTOMER\'S SOLE AND EXCLUSIVE REMEDY, FOR ANY INFRINGEMENT CLAIM.'
));

children.push(section('8.4 Customer Obligations.',
  'Customer is solely responsible for Customer Data and for ensuring that its use of the Subscription Services and the content of Customer Data complies with all applicable laws, regulations, and third-party rights. Customer represents and warrants that it has all rights, consents, and authorizations necessary to make Customer Data available to Lattice for the purposes contemplated by this Agreement.'
));

children.push(section('8.5 Indemnification Procedure.',
  'The indemnified Party will: (a) promptly notify the indemnifying Party in writing of any claim, provided that the failure to give prompt notice will not relieve the indemnifying Party of its obligations except to the extent the indemnifying Party is materially prejudiced thereby; (b) give the indemnifying Party sole control of the defense and settlement of the claim (provided that the indemnifying Party may not settle any claim that imposes any obligation or liability on the indemnified Party without the indemnified Party\'s prior written consent, not to be unreasonably withheld); and (c) provide reasonable cooperation in the defense, at the indemnifying Party\'s expense.'
));

children.push(section('8.6 Limitation of Liability.',
  'EXCEPT FOR (A) AMOUNTS OWED UNDER ANY ORDER FORM, (B) A PARTY\'S BREACH OF SECTION 7 (CONFIDENTIALITY), AND (C) LATTICE\'S OBLIGATIONS UNDER SECTION 8.3 (LATTICE IP INDEMNITY), IN NO EVENT WILL EITHER PARTY\'S TOTAL CUMULATIVE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT EXCEED THE FEES PAID OR PAYABLE BY CUSTOMER TO LATTICE UNDER THE APPLICABLE ORDER FORM IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE LIABILITY. THE LIABILITY CAP SET FORTH IN THIS SECTION 8.6 SHALL APPLY IN AGGREGATE TO ALL CAUSES OF ACTION (WHETHER IN CONTRACT, TORT, OR OTHERWISE), ALL THEORIES OF LIABILITY, AND ALL ORDER FORMS UNDER THIS AGREEMENT, AND SHALL APPLY EVEN IF THE STATED REMEDIES IN THIS AGREEMENT FAIL OF THEIR ESSENTIAL PURPOSE.'
));

children.push(section('8.7 Exclusion of Damages.',
  'IN NO EVENT WILL EITHER PARTY BE LIABLE TO THE OTHER PARTY FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR ANY LOST PROFITS, LOST REVENUE, LOST GOODWILL, LOST OR CORRUPTED DATA, OR COSTS OF SUBSTITUTE GOODS OR SERVICES, ARISING OUT OF OR RELATED TO THIS AGREEMENT, REGARDLESS OF THE FORM OR THEORY OF ACTION AND EVEN IF SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.'
));

// =========================================================================
// 9. SUBCONTRACTORS; INSURANCE; FORCE MAJEURE
// =========================================================================
children.push(heading('9. SUBCONTRACTORS; INSURANCE; FORCE MAJEURE'));

children.push(section('9.1 Subcontractors.',
  'Lattice may engage third parties to perform any of its obligations under this Agreement, including without limitation hosting, content delivery, support, and processing of Customer Data. Lattice will remain responsible for the performance of any such subcontractors and for compliance by such subcontractors with the applicable terms of this Agreement. Lattice is not required to provide advance notice to Customer of, or obtain Customer\'s consent to, the engagement, replacement, or termination of any subcontractor.'
));

children.push(section('9.2 Insurance.',
  'During the Subscription Term, Lattice will maintain at its own expense, at minimum, the following insurance coverage with insurers authorized to do business in the United States: (a) commercial general liability insurance with limits of not less than two million U.S. dollars ($2,000,000) per occurrence and in the aggregate; and (b) errors and omissions / professional liability insurance (which may include cyber liability coverage) with limits of not less than five million U.S. dollars ($5,000,000) per occurrence and in the aggregate. Upon Customer\'s written request, Lattice will provide a certificate of insurance evidencing such coverage.'
));

children.push(section('9.3 Force Majeure.',
  'Neither Party will be liable for any delay or failure to perform its obligations under this Agreement (other than payment obligations) to the extent such delay or failure is caused by an event beyond such Party\'s reasonable control, including without limitation acts of God, natural disasters, war, terrorism, civil unrest, pandemic, government action, labor disputes, or failures of third-party telecommunications, internet, or utility providers (a "Force Majeure Event"). The Party affected by a Force Majeure Event will: (a) provide prompt written notice to the other Party of the event and its expected duration; (b) use commercially reasonable efforts to mitigate the impact of the event; and (c) resume performance as soon as reasonably practicable. If a Force Majeure Event continues for more than sixty (60) consecutive days, either Party may terminate the affected Order Form upon written notice to the other Party.'
));

// =========================================================================
// 10. GENERAL
// =========================================================================
children.push(heading('10. GENERAL'));

children.push(section('10.1 Governing Law.',
  'This Agreement and any disputes arising out of or relating to it will be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict-of-laws principles. The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Agreement.'
));

children.push(section('10.2 Dispute Resolution; Arbitration.',
  'Except for actions seeking equitable relief, any dispute, claim, or controversy arising out of or relating to this Agreement, including the breach, termination, enforcement, interpretation, or validity thereof, or the determination of the scope or applicability of this agreement to arbitrate, will be resolved exclusively by final and binding arbitration administered by the American Arbitration Association under its Commercial Arbitration Rules. The arbitration will be conducted in San Francisco, California by a single arbitrator selected in accordance with such rules. Judgment on the award may be entered in any court having jurisdiction. Each Party will bear its own costs and fees in connection with the arbitration. THE PARTIES KNOWINGLY AND VOLUNTARILY WAIVE ANY RIGHT TO A TRIAL BY JURY AND ANY RIGHT TO PARTICIPATE IN A CLASS, COLLECTIVE, OR REPRESENTATIVE ACTION.'
));

children.push(section('10.3 Notices.',
  'All notices required or permitted under this Agreement will be in writing and will be deemed given upon (a) personal delivery, (b) the second business day after mailing by recognized overnight courier, or (c) the date of transmission if sent by email to the email address designated by the recipient Party in the applicable Order Form or otherwise in writing, provided that no automated bounce or non-delivery notification is received. Notices to Lattice shall be sent to legal@latticetelemetry.com with a copy to its principal place of business set forth in the preamble. Notices to Customer shall be sent to the email address and physical address designated in the applicable Order Form.'
));

children.push(section('10.4 Assignment.',
  'Neither Party may assign or transfer this Agreement, in whole or in part, without the prior written consent of the other Party, except that either Party may assign this Agreement without consent to an Affiliate or in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of its assets. Any purported assignment in violation of this Section 10.4 is void. This Agreement will be binding upon and inure to the benefit of the Parties and their permitted successors and assigns.'
));

children.push(section('10.5 Entire Agreement.',
  'This Agreement, together with all Order Forms, SOWs, and any addenda or exhibits attached hereto or referenced herein, constitutes the entire agreement between the Parties with respect to the subject matter hereof and supersedes all prior or contemporaneous agreements, understandings, or representations, whether written or oral, between the Parties regarding such subject matter. In the event of any conflict between this Agreement and an Order Form, the Order Form will control with respect to its subject matter only and only if it expressly references the conflicting term in this Agreement.'
));

children.push(section('10.6 Amendment; Waiver.',
  'No amendment to or modification of this Agreement will be effective unless in writing and signed by an authorized representative of each Party. The failure of a Party to enforce any provision of this Agreement will not constitute a waiver of such provision or of any other provision. No waiver of any breach of this Agreement will constitute a waiver of any other or subsequent breach.'
));

children.push(section('10.7 Independent Contractors.',
  'The Parties are independent contractors. Nothing in this Agreement will be construed to create a partnership, joint venture, employment, agency, or fiduciary relationship between the Parties. Neither Party has any authority to bind the other Party to any obligation.'
));

children.push(section('10.8 Severability.',
  'If any provision of this Agreement is held to be invalid, illegal, or unenforceable, the remaining provisions will remain in full force and effect, and the invalid, illegal, or unenforceable provision will be modified or limited to the minimum extent necessary to render it enforceable, while preserving as nearly as possible the original intent of the Parties.'
));

children.push(section('10.9 Counterparts; Electronic Signatures.',
  'This Agreement may be executed in counterparts, each of which will be deemed an original and all of which together will constitute one and the same instrument. Signatures transmitted by electronic means or via electronic signature platforms will have the same effect as original signatures.'
));

// ---------------------------------------------------------------------------
// Build & write
// ---------------------------------------------------------------------------
const doc = new Document({
  creator: 'Lattice Telemetry, Inc.',
  title: 'Master Subscription Agreement',
  description: 'SaaS Master Subscription Agreement',
  sections: [{ properties: {}, children }],
});

const buf = await Packer.toBuffer(doc);
fs.writeFileSync(OUT, buf);

// Word count (rough)
const allText = children
  .map((p) => p.options?.children?.map((r) => r.options?.text || '').join('') || '')
  .join(' ');
const wc = allText.split(/\s+/).filter(Boolean).length;

console.log(`Wrote ${OUT}`);
console.log(`Approx word count: ${wc}`);
console.log(`File size: ${buf.length} bytes`);
