// Round 1 rationale grader.
// For each finding in a run, classify materiality_rationale as
// MECHANICAL / GENERIC / CONTEXTUAL / EXEMPLARY using an LLM judge.
//
// Usage: node tools/contract-grader/grade_rationales.mjs <run-label-or-glob>
import fs from 'node:fs';
import path from 'node:path';

for (const line of fs.readFileSync('.env', 'utf8').split(/\r?\n/)) {
  const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
  if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
}
process.env.SUPABASE_URL = process.env.SUPABASE_URL || 'http://localhost';
process.env.SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || 'stub';
import dns from 'node:dns';
dns.setDefaultResultOrder('ipv4first');

import { callModel, extractJson } from '../../netlify/lib/anthropic.js';

const JUDGE_PROMPT = `You are a senior transactional attorney grading the *reasoning quality* of materiality rationales emitted by a contract-review tool. You will be given a finding's metadata and its materiality_rationale verbatim. You must classify the rationale into ONE of four buckets:

MECHANICAL — "Contract says X, playbook/standard says Y, change to Y." No engagement with deal context. The rationale could have been generated by a script doing string-matching against the playbook.

GENERIC — References general principles, industry norms, or standard concerns, but doesn't engage with this specific contract's structure or deal posture. Could appear identically on any other contract of this type.

CONTEXTUAL — Engages with this specific contract: references other clauses in the document, the deal posture (leverage), the client's role (buyer vs seller), the dollar value, or how the contract structure handles the risk. Cites specific provisions or shows reasoning grounded in the four corners.

EXEMPLARY — Reads like a partner-level memo. Articulates specific risk under this contract structure, weighs whether pushing is worth it given the leverage and the rest of the contract, and recommends specific action with reasoning grounded in the deal. Visibly engages with trade-offs.

Output ONLY a JSON object: { "quality": "MECHANICAL"|"GENERIC"|"CONTEXTUAL"|"EXEMPLARY", "explanation": "<one sentence>" }`;

async function gradeOne({ finding, runMeta }) {
  const userMessage =
    `RUN METADATA:\n` +
    `  profile: ${runMeta.profile_used}\n` +
    `  deal_posture: ${runMeta.deal_posture}\n` +
    `  client_role: ${runMeta.client_role}\n\n` +
    `FINDING:\n` +
    `  id: ${finding.id}\n` +
    `  specialist: ${finding.specialist || ''}\n` +
    `  category: ${finding.category || ''}\n` +
    `  severity: ${finding.severity}\n` +
    `  tier: ${finding.tier ?? ((finding.profile_refs||[]).length ? 1 : 2)}\n` +
    `  source_text: ${JSON.stringify((finding.source_text || '').slice(0, 200))}\n` +
    `  position: ${JSON.stringify((finding.position || '').slice(0, 200))}\n\n` +
    `MATERIALITY_RATIONALE (verbatim):\n${finding.materiality_rationale}\n\n` +
    `Classify and emit JSON.`;

  try {
    const resp = await callModel({
      agentName: 'rationale-grader',
      systemPrompt: JUDGE_PROMPT,
      userMessage,
      userId: 'grader',
      maxTokens: 200,
    });
    const parsed = extractJson(resp.text);
    return { quality: parsed?.quality || 'UNKNOWN', explanation: parsed?.explanation || '' };
  } catch (e) {
    return { quality: 'ERROR', explanation: e.message };
  }
}

async function gradeRun(runPath) {
  const r = JSON.parse(fs.readFileSync(runPath, 'utf8'));
  console.log(`[grader] grading ${path.basename(runPath)}: ${r.accepted_findings.length} findings`);
  const graded = [];
  for (const f of r.accepted_findings) {
    const res = await gradeOne({ finding: f, runMeta: r });
    graded.push({ ...f, _rationale_quality: res.quality, _rationale_explanation: res.explanation });
    console.log(`  ${f.id}: ${res.quality}`);
  }
  const dist = { MECHANICAL: 0, GENERIC: 0, CONTEXTUAL: 0, EXEMPLARY: 0, UNKNOWN: 0, ERROR: 0 };
  for (const f of graded) dist[f._rationale_quality] = (dist[f._rationale_quality] || 0) + 1;
  const out = { ...r, accepted_findings: graded, _rationale_quality_distribution: dist };
  const outPath = runPath.replace(/\.json$/, '.graded.json');
  fs.writeFileSync(outPath, JSON.stringify(out, null, 2));
  console.log(`[grader] -> ${outPath}  ·  ${JSON.stringify(dist)}`);
}

const target = process.argv[2];
if (!target) { console.error('Usage: node grade_rationales.mjs <run-label-or-path>'); process.exit(1); }

const runPath = target.endsWith('.json')
  ? path.resolve(target)
  : path.resolve(`tools/contract-grader/runs/${target}.json`);

await gradeRun(runPath);
