/**
 * Citation Verifier — Pass 5a form-check report generator.
 *
 * Per BUILD_SPEC §12.1: produces the Word .docx report that the drafting
 * attorney signs as the audit trail. Structure mirrors
 * imported-skill/report-template.md sections 1-9 + Appendix A + Appendix B.
 *
 * Why we hand-build with the `docx` package (vs. docxtemplater)
 * ------------------------------------------------------------
 * docxtemplater is great for filling pre-authored templates, but the
 * citation-verifier report has variable section counts (zero ✗ rows,
 * many ✗ rows, etc.) and the audit-trail tables expand row by row.
 * Hand-building with `docx` keeps the document deterministic and lets
 * us guarantee the OOXML emitted is the OOXML the attorney sees.
 *
 * Banned-phrase rule (BUILD_SPEC §16): every flag.message and
 * suggested_fix is sanitized before reaching this module — but we
 * defensively sanitize again here. Belt-and-suspenders.
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  AlignmentType,
  PageBorderOffsetFrom,
} from 'docx';
import { sanitizeOutput } from './skill-prompt.js';
import { formatCitationDisplay } from './display.js';
import { disclaimerParagraphs, DOCUMENT_STYLES } from '../review-summary.js';

// Match the contract-review summary's letterhead-style page borders so the
// two downloads read as siblings from the same firm.
const PAGE_BORDER_OPTS = {
  pageBorders: { offsetFrom: PageBorderOffsetFrom.PAGE },
  pageBorderTop:    { style: BorderStyle.SINGLE, size: 12, color: '1A1A1A', space: 24 },
  pageBorderBottom: { style: BorderStyle.SINGLE, size: 12, color: '1A1A1A', space: 24 },
  pageBorderLeft:   { style: BorderStyle.SINGLE, size: 12, color: '1A1A1A', space: 24 },
  pageBorderRight:  { style: BorderStyle.SINGLE, size: 12, color: '1A1A1A', space: 24 },
};
const PAGE_MARGINS = { top: 1080, right: 1080, bottom: 1080, left: 1080 };

const AUTHOR = 'Legal Overflow — Citation Verifier';
const PROTOCOL_VERSION = '1.1.0';
const DISCLAIMER =
  'This report records form-checking against Bluebook 22nd Edition only. It does NOT attest to the substantive ' +
  'accuracy of any authority cited. Existence checks use CourtListener, which does not include every state ' +
  'opinion, recent unpublished disposition, or sealed matter. Please verify each citation independently before ' +
  'filing. This is attorney work product prepared in anticipation of filing.';

/**
 * Build the form-check report .docx.
 *
 * @param {object} args
 * @param {object} args.run            — verification_runs row
 * @param {Array}  args.citations      — classified citations enriched with flags + existence
 * @param {Array}  args.documentFlags  — Pass 4 cross-citation flags (no specific citation)
 * @returns {Promise<Buffer>} — .docx buffer ready to upload to Storage
 */
export async function buildFormReport({ run, citations, documentFlags = [] }) {
  const summary = computeSummary(citations, documentFlags);

  const sections = [
    {
      properties: {
        page: { margin: PAGE_MARGINS, borders: PAGE_BORDER_OPTS },
      },
      children: [
        ...header(run, summary),
        ...summaryTable(summary),
        ...nonConformingSection(citations),
        ...needsCorrectionSection(citations),
        ...conformingSection(summary),
        ...existenceSection(citations),
        ...aggregateFindingsSection(citations, documentFlags),
        ...correctiveActionChecklist(),
        ...senorCounselSection(citations, documentFlags),
        ...signOffBlock(),
        ...appendixA(citations),
        ...appendixB(citations),
        // Bluebook-specific protocol caveat (existing)
        ...disclaimerFooter(),
        // Shared "not legal advice / AI / qualified counsel" disclaimer
        // — same block the contract-review summary uses, for consistency.
        ...disclaimerParagraphs(),
      ],
    },
  ];

  const doc = new Document({
    creator: AUTHOR,
    title: `Citation Form-Check Report — ${run.file_name}`,
    description: 'Bluebook 22e form-check report generated by Legal Overflow.',
    styles: DOCUMENT_STYLES,
    sections,
  });

  return await Packer.toBuffer(doc);
}

// ---------------------------------------------------------------------------
// Sections (each returns an array of Paragraphs/Tables to be concatenated)
// ---------------------------------------------------------------------------

function header(run, summary) {
  return [
    h1('CITATION FORM-CHECK REPORT'),
    p('Bluebook 22nd Edition — form verification', { italics: true, alignment: AlignmentType.CENTER }),
    p(''),
    keyValue('Document', run.file_name),
    keyValue('Format', run.file_format.toUpperCase()),
    keyValue('Style applied', run.style === 'whitepages' ? 'White-pages (scholarly)' : 'Bluepages (practitioner)'),
    keyValue('Ruleset', run.ruleset || 'federal'),
    keyValue('Bluebook edition', run.bluebook_edition || '22e'),
    keyValue('Protocol version', PROTOCOL_VERSION),
    keyValue('Run ID', run.id),
    keyValue('Generated', new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC'),
    p(''),
    p(
      'This report does not reproduce Bluebook text. Every finding below is anchored to a specific Bluebook ' +
      'rule or table number for attorney audit against the Bluebook itself.',
      { italics: true }
    ),
    p(''),
  ];
}

function summaryTable(s) {
  return [
    h2('1. Summary'),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        tableRow(['Tier', 'Count', 'Percent of total'], { header: true }),
        tableRow(['✓ CONFORMING',     String(s.conforming),    pct(s.conforming, s.total)]),
        tableRow(['▲ NEEDS CORRECTION', String(s.review),      pct(s.review, s.total)]),
        tableRow(['✗ NON-CONFORMING', String(s.nonConforming), pct(s.nonConforming, s.total)]),
        tableRow(['Total',             String(s.total),         '100%'], { header: true }),
      ],
    }),
    p(''),
    p(`Status at time of report: ${s.statusLabel}`, { bold: true }),
    p(''),
  ];
}

function nonConformingSection(citations) {
  const rows = citations
    .map((c, i) => ({ c, i, flags: (c.flags || []).filter((f) => f.severity === 'non_conforming') }))
    .filter((x) => x.flags.length > 0);

  if (rows.length === 0) {
    return [h2('2. Non-conforming citations (✗)'), p('None.'), p('')];
  }

  const tableRows = [
    tableRow(['#', 'Citation as it appears', 'Location', 'Rule(s) violated', 'Failure finding', 'Required action'], { header: true }),
  ];
  for (const { c, i, flags } of rows) {
    const ruleCites = flags.map((f) => f.rule_cite).filter(Boolean).join('; ');
    const findings = flags.map((f) => sanitizeOutput(f.message)).join(' / ');
    const actions = flags.map((f) => f.suggested_fix ? sanitizeOutput(f.suggested_fix) : 'Re-source or rewrite.').join(' / ');
    tableRows.push(tableRow([
      String(i + 1),
      formatCitationDisplay(c),
      locationOf(c),
      ruleCites || '—',
      findings,
      actions,
    ]));
  }

  return [
    h2(`2. Non-conforming citations (✗) — ${rows.length}`),
    p(
      `The draft contains ${rows.length} citation(s) that do not conform to Bluebook 22e form. Each must be re-sourced, ` +
      'rewritten, or removed before the filing is signed.'
    ),
    p(''),
    new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: tableRows }),
    p(''),
  ];
}

function needsCorrectionSection(citations) {
  const rows = citations
    .map((c, i) => ({ c, i, flags: (c.flags || []).filter((f) => f.severity === 'review') }))
    .filter((x) => x.flags.length > 0);

  if (rows.length === 0) {
    return [h2('3. Citations needing correction (▲)'), p('None.'), p('')];
  }

  const tableRows = [
    tableRow(['#', 'Citation as it appears', 'Location', 'Rule(s) implicated', 'Finding', 'Corrected form'], { header: true }),
  ];
  for (const { c, i, flags } of rows) {
    const ruleCites = flags.map((f) => f.rule_cite).filter(Boolean).join('; ');
    const findings = flags.map((f) => sanitizeOutput(f.message)).join(' / ');
    const fixes = flags.map((f) => f.suggested_fix ? sanitizeOutput(f.suggested_fix) : '—').join(' / ');
    tableRows.push(tableRow([
      String(i + 1),
      formatCitationDisplay(c),
      locationOf(c),
      ruleCites || '—',
      findings,
      fixes,
    ]));
  }

  return [
    h2(`3. Citations needing correction (▲) — ${rows.length}`),
    p(
      `The draft contains ${rows.length} citation(s) that deviate from Bluebook 22e form but are traceable to verifiable authority. ` +
      'Each must be corrected and re-verified.'
    ),
    p(''),
    new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: tableRows }),
    p(''),
  ];
}

function conformingSection(s) {
  return [
    h2('4. Conforming citations (✓)'),
    p(`${s.conforming} citation(s) passed every applicable Bluebook 22e form test. The full table is appended as Appendix A.`),
    p(''),
  ];
}

function existenceSection(citations) {
  const notFound = citations.filter((c) => c.existence?.status === 'existence_not_found');
  const uncertain = citations.filter((c) => c.existence?.status === 'existence_uncertain');

  if (notFound.length === 0 && uncertain.length === 0) {
    return [
      h2('5. Existence-check findings'),
      p('All case citations were located in CourtListener.'),
      p(''),
    ];
  }

  const result = [
    h2(`5. Existence-check findings — ${notFound.length} not found, ${uncertain.length} uncertain`),
    p(
      'These citations could not be located in CourtListener. CourtListener does not include every state opinion, ' +
      'recent unpublished disposition, or sealed matter. Please verify each citation before filing.',
      { italics: true }
    ),
    p(''),
  ];

  const allRows = [...notFound, ...uncertain];
  const tableRows = [
    tableRow(['#', 'Citation', 'Location', 'Status', 'CourtListener search'], { header: true }),
  ];
  for (let i = 0; i < allRows.length; i++) {
    const c = allRows[i];
    tableRows.push(tableRow([
      String(i + 1),
      formatCitationDisplay(c),
      locationOf(c),
      c.existence?.status === 'existence_not_found' ? 'Not located' : 'Uncertain',
      c.existence?.search_url || '—',
    ]));
  }
  result.push(new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: tableRows }));
  result.push(p(''));
  return result;
}

function aggregateFindingsSection(citations, documentFlags) {
  const allFlags = [
    ...citations.flatMap((c) => (c.flags || []).map((f) => ({ ...f, _citation: c }))),
    ...documentFlags.map((f) => ({ ...f })),
  ];

  const groups = {
    abbreviations: 'Abbreviations (R. 10.2 / T6; T10)',
    reporter: 'Reporter, court, and date (R. 10.3-10.5; T1)',
    short_form: 'Short forms and id. (R. 4; R. 10.9)',
    signal: 'Introductory signals and ordering (R. 1.2-1.4)',
    parenthetical: 'Parentheticals (R. 1.5; R. 10.6)',
    quotation: 'Quotations (R. 5)',
    history: 'Prior and subsequent history (R. 10.7; T8)',
    parallel: 'Parallel citations (R. 10.3.2)',
    capitalization: 'Capitalization in the text (R. 8)',
    existence: 'Existence checks (CourtListener)',
    form_components: 'Form components (R. 10.1)',
  };

  const out = [h2('6. Aggregate form findings')];

  for (const [key, label] of Object.entries(groups)) {
    const fs = allFlags.filter((f) => f.category === key);
    out.push(p(label, { bold: true }));
    if (fs.length === 0) {
      out.push(bullet('(none observed)'));
    } else {
      for (const f of fs) {
        out.push(bullet(`[${f.severity}] ${sanitizeOutput(f.message)}` + (f.rule_cite ? ` (${f.rule_cite})` : '')));
      }
    }
    out.push(p(''));
  }

  return out;
}

function correctiveActionChecklist() {
  const items = [
    'Re-source, rewrite, or remove every ✗ citation listed in §2.',
    'Re-run the protocol on any substitute citation before inserting it.',
    'Implement every correction listed in §3 and re-verify.',
    'Verify every citation flagged in §5 (existence-check) against the original source.',
    'Recheck short-form and id. usage after any citation insertion or deletion (R. 4; R. 10.9).',
    'Reconfirm pagination, pin-cites, and tables of authorities after all corrections.',
    'Complete the Bluebook form-check drafting sign-off (§9).',
    'File this report and the signed sign-off in the matter file.',
  ];
  return [
    h2('7. Corrective-action checklist'),
    ...items.map((t) => bullet(`☐ ${t}`)),
    p(''),
  ];
}

function senorCounselSection(citations, documentFlags) {
  const escalations = [
    ...citations.flatMap((c) => (c.flags || []).filter((f) => f.severity === 'non_conforming')),
    ...documentFlags.filter((f) => f.severity === 'non_conforming'),
  ];
  return [
    h2('8. Items requiring senior-counsel attention'),
    escalations.length === 0
      ? p('(none)')
      : p(`${escalations.length} non-conforming finding(s) above require senior-counsel attention before sign-off.`),
    p(''),
  ];
}

function signOffBlock() {
  return [
    h2('9. Drafting sign-off'),
    p(
      'I confirm that the form of the citations in the document identified on page 1 has been verified against the ' +
      'Twenty-Second Edition of The Bluebook: A Uniform System of Citation, and that no citation remaining in the ' +
      'document is flagged ✗ or ▲ at the time of this signature.',
      { italics: true }
    ),
    p(''),
    p('Drafting / supervising attorney: ____________________________'),
    p(''),
    p('Bar number / jurisdiction: _________________________________'),
    p(''),
    p('Signature: ___________________________  Date: ______________'),
    p(''),
  ];
}

function appendixA(citations) {
  const headers = ['#', 'Citation', 'Type', 'Tier', 'Existence', 'Finding / action'];
  const rows = [tableRow(headers, { header: true })];

  for (let i = 0; i < citations.length; i++) {
    const c = citations[i];
    const tier = tierOf(c);
    const finding = (c.flags || []).map((f) => sanitizeOutput(f.message)).join(' / ') || '✓ pass';
    rows.push(tableRow([
      String(i + 1),
      formatCitationDisplay(c),
      c.citation_type || 'unknown',
      tier,
      existenceLabel(c.existence),
      finding,
    ]));
  }

  return [
    h2('Appendix A — Per-citation verification table'),
    new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows }),
    p(''),
  ];
}

function appendixB(citations) {
  const rows = [tableRow(['#', 'Citation', 'Type', 'Governing rule(s)', 'Tables', 'Pin-cite'], { header: true })];
  for (let i = 0; i < citations.length; i++) {
    const c = citations[i];
    rows.push(tableRow([
      String(i + 1),
      formatCitationDisplay(c),
      c.citation_type || 'unknown',
      c.governing_rule || '—',
      c.governing_table || '—',
      (c.components && c.components.pin_cite) || '—',
    ]));
  }
  return [
    h2('Appendix B — Rule-map log'),
    new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows }),
    p(''),
  ];
}

function disclaimerFooter() {
  return [
    p(''),
    p('— — —', { alignment: AlignmentType.CENTER }),
    p(DISCLAIMER, { italics: true }),
  ];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function computeSummary(citations, documentFlags) {
  let conforming = 0, review = 0, nonConforming = 0;
  for (const c of citations) {
    const tier = tierOf(c);
    if (tier === '✓') conforming++;
    else if (tier === '▲') review++;
    else if (tier === '✗') nonConforming++;
  }
  // Document-level flags inherit their severity straight up — they don't
  // re-shade per-citation tiers, but they do bump the global ▲/✗ counts.
  for (const f of documentFlags) {
    if (f.severity === 'review') review++;
    else if (f.severity === 'non_conforming') nonConforming++;
  }
  const total = citations.length;
  const statusLabel = nonConforming > 0
    ? 'Draft NOT cleared for filing — open ✗ items remain'
    : review > 0
      ? 'Corrections pending drafting review'
      : 'Cleared for drafting sign-off upon completion of attestation packet';
  return { total, conforming, review, nonConforming, statusLabel };
}

function tierOf(c) {
  const flags = c.flags || [];
  if (flags.some((f) => f.severity === 'non_conforming')) return '✗';
  if (flags.some((f) => f.severity === 'review')) return '▲';
  return '✓';
}

function locationOf(c) {
  const parts = [];
  if (c.page_number != null) parts.push(`p.${c.page_number}`);
  if (c.in_footnote && c.footnote_num != null) parts.push(`fn.${c.footnote_num}`);
  if (c.char_start != null) parts.push(`@${c.char_start}`);
  return parts.join(' / ') || '—';
}

function existenceLabel(e) {
  if (!e) return '—';
  switch (e.status) {
    case 'existence_verified': return '✓ found';
    case 'existence_not_found': return 'not found';
    case 'existence_uncertain': return 'uncertain';
    case 'not_applicable': return 'n/a';
    default: return '—';
  }
}

function pct(n, total) {
  if (!total) return '0%';
  return `${Math.round((n / total) * 100)}%`;
}

// docx-package shorthand wrappers
function h1(text) { return new Paragraph({ heading: HeadingLevel.HEADING_1, alignment: AlignmentType.CENTER, children: [new TextRun({ text, bold: true, size: 32 })] }); }
function h2(text) { return new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text, bold: true, size: 26 })] }); }
function p(text, opts = {}) {
  return new Paragraph({
    alignment: opts.alignment,
    children: [new TextRun({
      text,
      bold: !!opts.bold,
      italics: !!opts.italics,
    })],
  });
}
function bullet(text) {
  return new Paragraph({
    bullet: { level: 0 },
    children: [new TextRun({ text })],
  });
}
function keyValue(key, value) {
  return new Paragraph({
    children: [
      new TextRun({ text: `${key}: `, bold: true }),
      new TextRun({ text: String(value ?? '—') }),
    ],
  });
}
function tableRow(cells, opts = {}) {
  return new TableRow({
    tableHeader: !!opts.header,
    children: cells.map((cellText) => new TableCell({
      width: { size: Math.floor(10000 / cells.length), type: WidthType.DXA },
      children: [new Paragraph({ children: [new TextRun({ text: String(cellText ?? ''), bold: !!opts.header })] })],
    })),
  });
}
