/**
 * Review summary generator — produces the internal "Review_Summary.docx"
 * that goes alongside the customer-facing annotated file.
 *
 * This is an INTERNAL-ONLY document (CLAUDE.md §4.3). It MAY reference
 * profile clauses and severity tiers — those are the things the customer-
 * facing annotations are forbidden from containing.
 *
 * Input: the compiled findings array + review metadata.
 * Output: a .docx Buffer.
 */
import {
  Document, Packer, Paragraph, HeadingLevel, TextRun, Table, TableRow, TableCell,
  WidthType, AlignmentType, BorderStyle, PageBorderOffsetFrom,
} from 'docx';
import { humanize } from './text-utils.js';

// ====================================================================
// Document styling — applied uniformly across the review summary and
// the citation-verifier checklist so both downloads share a single
// "this is the firm's letterhead" feel.
// ====================================================================

// Subtle dark-gray page border. Drawn on all four sides, offset from
// the page edge (not the text edge) so it reads as letterhead, not as
// a frame around the content.
const PAGE_BORDER_OPTS = {
  pageBorders: { offsetFrom: PageBorderOffsetFrom.PAGE },
  pageBorderTop:    { style: BorderStyle.SINGLE, size: 12, color: '1A1A1A', space: 24 },
  pageBorderBottom: { style: BorderStyle.SINGLE, size: 12, color: '1A1A1A', space: 24 },
  pageBorderLeft:   { style: BorderStyle.SINGLE, size: 12, color: '1A1A1A', space: 24 },
  pageBorderRight:  { style: BorderStyle.SINGLE, size: 12, color: '1A1A1A', space: 24 },
};

// Generous page margins so the body text breathes inside the border.
const PAGE_MARGINS = { top: 1080, right: 1080, bottom: 1080, left: 1080 };

// Shared document styles — Times New Roman everywhere; headings bold + pure
// black (the docx default for HEADING_1/2 is a navy that reads as colored
// brand styling, which we don't want for a formal-memo voice). Exported so
// the citation-verifier report applies the identical typography.
export const DOCUMENT_STYLES = {
  default: {
    document: {
      run: { font: 'Times New Roman', size: 22 }, // size is half-points → 11pt
    },
    title: {
      run: { font: 'Times New Roman', bold: true, color: '000000', size: 36 },
      paragraph: { spacing: { after: 200 } },
    },
    heading1: {
      run: { font: 'Times New Roman', bold: true, color: '000000', size: 28 },
      paragraph: { spacing: { before: 240, after: 120 } },
    },
    heading2: {
      run: { font: 'Times New Roman', bold: true, color: '000000', size: 24 },
      paragraph: { spacing: { before: 160, after: 80 } },
    },
    heading3: {
      run: { font: 'Times New Roman', bold: true, color: '000000', size: 22 },
      paragraph: { spacing: { before: 120, after: 60 } },
    },
  },
  paragraphStyles: [
    {
      id: 'Normal',
      name: 'Normal',
      run: { font: 'Times New Roman', size: 22 },
    },
  ],
};

// A horizontal rule we render as an empty paragraph with a bottom border.
function horizontalRule({ before = 80, after = 120 } = {}) {
  return new Paragraph({
    spacing: { before, after },
    border: {
      bottom: { style: BorderStyle.SINGLE, size: 6, color: '1A1A1A', space: 1 },
    },
  });
}

/**
 * The standard disclaimer block. Same wording on both the review summary
 * and the citation-verifier checklist so the user sees consistent language
 * about AI limitations + the need for qualified counsel review.
 */
export function disclaimerParagraphs() {
  const out = [];
  out.push(horizontalRule({ before: 240, after: 120 }));
  out.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: 'IMPORTANT — DISCLAIMER', bold: true, size: 22 })],
    spacing: { after: 120 },
  }));
  const lines = [
    'This document is generated by an automated AI system and is provided for informational purposes only.',
    'It is NOT legal advice and does not create an attorney-client relationship.',
    'AI-generated analysis is necessarily limited and may miss material issues, misinterpret context, or contain factual errors.',
    'Do NOT rely on this document as a substitute for review by qualified counsel.',
    'Before signing, executing, or otherwise acting on any contract or finding addressed here, consult a licensed attorney admitted to practice in the relevant jurisdiction. The recipient assumes all risk associated with use of this analysis.',
  ];
  for (const line of lines) {
    out.push(new Paragraph({
      children: [new TextRun({ text: line, italics: true, size: 18 })],
      spacing: { after: 80 },
    }));
  }
  return out;
}

/**
 * Memo-style document header. Centered title, subhead with reviewer/date,
 * horizontal rule. Used by both the review summary and the citation
 * checklist so the two documents read as siblings.
 *
 * @param {object} opts
 * @param {string} opts.title       — top-line heading (e.g. "CONTRACT REVIEW MEMORANDUM")
 * @param {string} [opts.subject]   — optional "RE:" line
 * @param {string} [opts.preparedBy] — name shown after "Prepared by"
 * @param {string} opts.dateStr     — formatted date string
 */
export function memoHeaderParagraphs({ title, subject, preparedBy, dateStr }) {
  const out = [];
  out.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: title, bold: true, size: 32 })],
    spacing: { after: 80 },
  }));
  const subParts = [];
  if (preparedBy) subParts.push(`Prepared by ${preparedBy}`);
  if (dateStr) subParts.push(dateStr);
  if (subParts.length) {
    out.push(new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: subParts.join('  ·  '), size: 18 })],
      spacing: { after: 80 },
    }));
  }
  out.push(horizontalRule({ before: 0, after: 200 }));
  if (subject) {
    out.push(new Paragraph({
      children: [
        new TextRun({ text: 'RE:  ', bold: true, size: 22 }),
        new TextRun({ text: subject, size: 22 }),
      ],
      spacing: { after: 200 },
    }));
  }
  return out;
}

// Mirrors the UI's SEVERITY_LABELS map so the downloadable summary speaks
// the same human labels the customer sees in the dashboard.
const SEVERITY_LABEL = {
  blocker:  'Red flag',
  major:    'Material',
  moderate: 'Worth flagging',
  minor:    'Note for record',
};
const sevLabel = (s) => SEVERITY_LABEL[String(s || '').toLowerCase()] || (s ? humanize(s) : '—');

/**
 * @param {object} opts
 * @param {string} opts.filename       — original contract filename
 * @param {string} opts.contractType   — from classifier
 * @param {string} opts.pipelineMode   — express | standard | comprehensive
 * @param {Array<Finding>} opts.findings
 * @param {Array<Finding>} opts.unanchored — findings that could not be placed
 * @param {object} opts.severityCounts
 * @param {Date}   opts.reviewedAt
 * @returns {Promise<Buffer>}
 */
export async function buildReviewSummaryDocx({
  filename,
  contractType,
  pipelineMode,
  findings,
  priorityThree = [],
  coveragePassAggregate = [],
  rejectedFindings = [],
  specialistFailures = [],
  expectedSpecialists = [],
  unanchored = [],
  severityCounts,
  reviewedAt,
}) {
  const date = (reviewedAt || new Date()).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const children = [];

  // Memo-style header. Per user direction, no personal-name attribution
  // appears on the deliverable. The "AI-drafted" by-line keeps the
  // honesty signal required by Florida Rule 4-7.13 without identifying
  // any specific reviewer on the document.
  children.push(...memoHeaderParagraphs({
    title: 'CONTRACT REVIEW MEMORANDUM',
    subject: `${filename}  —  ${humanize(contractType) || 'Unclassified'}`,
    preparedBy: 'AI-drafted contract analysis',
    dateStr: date,
  }));

  // Up-front warning paragraph — appears on page 1 immediately after the
  // memo header, before any findings. The full disclaimer block still
  // appears at the end of the document.
  children.push(new Paragraph({
    spacing: { before: 0, after: 200 },
    children: [
      new TextRun({
        text: 'NOTICE: This document was drafted by an automated AI system. It is NOT legal advice and has NOT been independently reviewed by a licensed attorney. Before sending, signing, filing, or otherwise acting on any finding here, you must independently review the analysis and, where appropriate, consult qualified counsel. See the full disclaimer at the end of this document.',
        italics: true,
        size: 18,
      }),
    ],
  }));

  // Severity summary
  children.push(new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [new TextRun('Severity summary')],
  }));

  children.push(new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      tableRow(['Severity', 'Count'], true),
      tableRow(['Red flag',        String(severityCounts?.blocker  || 0)]),
      tableRow(['Material',        String(severityCounts?.major    || 0)]),
      tableRow(['Worth flagging',  String(severityCounts?.moderate || 0)]),
      tableRow(['Note for record', String(severityCounts?.minor    || 0)]),
    ],
  }));
  children.push(new Paragraph({ children: [new TextRun('')] }));

  // Specialist failures — if ANY specialist didn't contribute, the review is
  // incomplete in that specialist's domain and the reviewer needs to know up
  // front. Rendered BEFORE Top 3 so it's impossible to miss. Section omitted
  // entirely when there are no failures.
  if (specialistFailures && specialistFailures.length > 0) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: '⚠ Specialist failures — this review is INCOMPLETE', bold: true })],
    }));
    children.push(new Paragraph({
      children: [new TextRun({
        text:
          'One or more specialists did not contribute coverage to this review. The clauses in their domains have NOT been audited. Do not rely on the rest of this review for those clause types until the failed specialists are rerun. Common causes: the specialist errored, returned non-JSON, or returned an empty coverage_pass (which the master template forbids).',
        italics: true,
      })],
    }));
    if (expectedSpecialists && expectedSpecialists.length > 0) {
      children.push(new Paragraph({
        children: [
          new TextRun({ text: 'Expected specialists for this pipeline: ', bold: true }),
          new TextRun(expectedSpecialists.join(', ')),
        ],
      }));
      children.push(new Paragraph({ children: [new TextRun('')] }));
    }
    for (const f of specialistFailures) {
      children.push(new Paragraph({
        children: [
          new TextRun({ text: '• ' + (humanize(f.specialist) || '(unknown)'), bold: true }),
        ],
      }));
      children.push(new Paragraph({
        children: [new TextRun({ text: '   Reason: ' + (f.reason || 'no reason recorded'), italics: true })],
      }));
    }
    children.push(new Paragraph({ children: [new TextRun('')] }));
  }

  // Top 3 to Raise — phone-call-level summary (FIRST section per partner request)
  if (priorityThree && priorityThree.length > 0) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun('Top 3 to raise')],
    }));
    children.push(new Paragraph({
      children: [new TextRun({
        text: 'Partner-level summary. Raise these on a call with the counterparty before sending the full redline.',
        italics: true,
      })],
    }));
    priorityThree.slice(0, 3).forEach((f, i) => {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: `${i + 1}. [${sevLabel(f.severity)}] ${humanize(f.category) || '—'} · ${f.location || 'Unlocated'}` })],
      }));
      if (f.materiality_rationale) {
        children.push(new Paragraph({
          children: [new TextRun({ text: 'Why: ', bold: true }), new TextRun(f.materiality_rationale)],
        }));
      }
      if (f.position) {
        children.push(new Paragraph({
          children: [new TextRun({ text: 'Position (opening ask): ', bold: true }), new TextRun(f.position)],
        }));
      }
      if (f.fallback) {
        children.push(new Paragraph({
          children: [new TextRun({ text: 'Fallback: ', bold: true }), new TextRun(f.fallback)],
        }));
      }
      if (f.walkaway) {
        children.push(new Paragraph({
          children: [new TextRun({ text: 'Walkaway: ', bold: true }), new TextRun(f.walkaway)],
        }));
      }
      children.push(new Paragraph({ children: [new TextRun('')] }));
    });
  }

  // Senior-review callouts first (per CLAUDE.md §7)
  const seniorFindings = findings.filter(f => f.requires_senior_review);
  if (seniorFindings.length > 0) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun('Requires senior review')],
    }));
    for (const f of seniorFindings) {
      children.push(...renderFinding(f));
    }
    children.push(new Paragraph({ children: [new TextRun('')] }));
  }

  // Full findings list
  children.push(new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [new TextRun('All findings')],
  }));

  // Sort: Blocker > Major > Moderate > Minor; within severity, keep original order
  const sevOrder = { Blocker: 0, Major: 1, Moderate: 2, Minor: 3 };
  const sorted = [...findings].sort((a, b) => (sevOrder[a.severity] ?? 99) - (sevOrder[b.severity] ?? 99));
  for (const f of sorted) {
    children.push(...renderFinding(f));
  }

  // Unanchored findings (CLAUDE.md §4.8 — never silently dropped)
  if (unanchored.length > 0) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun('Unanchored findings — manual placement required')],
    }));
    children.push(new Paragraph({
      children: [new TextRun({
        text: 'The following findings could not be anchored to text in the source document. Please review and place manually before sending.',
        italics: true,
      })],
    }));
    for (const f of unanchored) {
      children.push(...renderFinding(f, { unanchored: true }));
    }
  }

  // Coverage pass — grouped by specialist, internal audit trail
  if (coveragePassAggregate && coveragePassAggregate.length > 0) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun('Coverage pass (internal audit trail)')],
    }));
    children.push(new Paragraph({
      children: [new TextRun({
        text: 'Every specialist is required to enumerate the hard-requirement items in its domain and state what it checked, whether it found the item present, absent, cross-referenced to a master agreement, partially addressed, or not applicable. Silence is not acceptable — items checked and found fine are the majority of entries.',
        italics: true,
      })],
    }));
    const bySpecialist = {};
    for (const entry of coveragePassAggregate) {
      const key = entry.specialist || 'unknown';
      (bySpecialist[key] ||= []).push(entry);
    }
    for (const [spec, entries] of Object.entries(bySpecialist)) {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: humanize(spec) })],
      }));
      for (const e of entries) {
        children.push(new Paragraph({
          children: [
            new TextRun({ text: `• [${humanize(e.status) || '—'}] ${e.item || '—'}`, bold: true }),
          ],
        }));
        if (e.source) {
          children.push(new Paragraph({
            children: [new TextRun({ text: `   Source: ${humanize(e.source)}${e.profile_ref ? ` (${e.profile_ref})` : ''}${e.playbook_fit ? ` — Playbook fit: ${humanize(e.playbook_fit)}` : ''}`, italics: true })],
          }));
        }
        if (e.evidence) {
          children.push(new Paragraph({
            children: [new TextRun({ text: `   evidence: ${e.evidence}`, italics: true })],
          }));
        }
      }
      children.push(new Paragraph({ children: [new TextRun('')] }));
    }
  }

  // Rejected findings — audit trail of what got dropped and why
  if (rejectedFindings && rejectedFindings.length > 0) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun('Rejected findings (audit trail)')],
    }));
    children.push(new Paragraph({
      children: [new TextRun({
        text: 'Findings the pipeline dropped during compilation, posture-integrity, proportionality, or schema validation. Included for audit and calibration — not part of the redline.',
        italics: true,
      })],
    }));
    for (const f of rejectedFindings) {
      const rejTag = humanize(f.rejection_source || (f.rejection_reason ? 'rejected' : 'rejected'));
      children.push(new Paragraph({
        children: [
          new TextRun({ text: `• [${rejTag}] ${humanize(f.category) || '—'} · ${humanize(f.specialist) || '—'}`, bold: true }),
        ],
      }));
      if (f.rejection_reason) {
        children.push(new Paragraph({
          children: [new TextRun({ text: `   reason: ${f.rejection_reason}`, italics: true })],
        }));
      }
      if (f.source_text) {
        children.push(new Paragraph({
          children: [new TextRun({ text: `   Source: "${String(f.source_text).slice(0, 240)}${f.source_text.length > 240 ? '…' : ''}"`, italics: true })],
        }));
      }
    }
  }

  // Append the disclaimer block at the very end of the document so it
  // shows up on the last page after every finding.
  children.push(...disclaimerParagraphs());

  const doc = new Document({
    creator: 'Legal Overflow',
    title: 'Contract Review Summary',
    styles: DOCUMENT_STYLES,
    sections: [{
      properties: {
        page: {
          margin: PAGE_MARGINS,
          borders: PAGE_BORDER_OPTS,
        },
      },
      children,
    }],
  });

  return await Packer.toBuffer(doc);
}

function tableRow(cells, header = false) {
  return new TableRow({
    children: cells.map(c => new TableCell({
      children: [new Paragraph({
        children: [new TextRun({ text: c, bold: header })],
      })],
    })),
  });
}

function renderFinding(f, opts = {}) {
  const out = [];
  const existentialTag = f.existential ? ' [EXISTENTIAL]' : '';
  const title = `[${sevLabel(f.severity)}]${existentialTag} ${humanize(f.category) || '—'} · ${f.location || 'Unlocated'}`;
  out.push(new Paragraph({
    heading: HeadingLevel.HEADING_2,
    children: [new TextRun({ text: title })],
  }));

  if (f.specialist || f.jurisdiction_assumed) {
    const parts = [];
    if (f.specialist) parts.push(`Specialist: ${humanize(f.specialist)}`);
    if (f.jurisdiction_assumed) parts.push(`Jurisdiction assumed: ${f.jurisdiction_assumed}`);
    out.push(new Paragraph({
      children: [new TextRun({ text: parts.join('  ·  '), italics: true })],
    }));
  }

  if (f.materiality_rationale) {
    out.push(new Paragraph({
      children: [new TextRun({ text: 'Materiality: ', bold: true }), new TextRun(f.materiality_rationale)],
    }));
  }
  if (f.internal_note) {
    out.push(new Paragraph({
      children: [new TextRun({ text: 'Why it matters: ', bold: true }), new TextRun(f.internal_note)],
    }));
  }
  if (f.position) {
    out.push(new Paragraph({
      children: [new TextRun({ text: 'Position (opening ask): ', bold: true }), new TextRun(f.position)],
    }));
  }
  if (f.fallback) {
    out.push(new Paragraph({
      children: [new TextRun({ text: 'Fallback: ', bold: true }), new TextRun(f.fallback)],
    }));
  }
  if (f.walkaway) {
    out.push(new Paragraph({
      children: [new TextRun({ text: 'Walkaway: ', bold: true }), new TextRun(f.walkaway)],
    }));
  }
  if (f.source_text) {
    out.push(new Paragraph({
      children: [new TextRun({ text: 'Source text: ', bold: true })],
    }));
    out.push(new Paragraph({
      children: [new TextRun({ text: `"${f.source_text}"`, italics: true })],
    }));
  }
  if (f.suggested_text) {
    out.push(new Paragraph({
      children: [new TextRun({ text: 'Proposed language: ', bold: true })],
    }));
    out.push(new Paragraph({
      children: [new TextRun({ text: `"${f.suggested_text}"`, italics: true })],
    }));
  }
  if (f.external_comment) {
    out.push(new Paragraph({
      children: [new TextRun({ text: 'Margin comment (customer-facing): ', bold: true })],
    }));
    out.push(new Paragraph({ children: [new TextRun(f.external_comment)] }));
  }
  if (f.profile_refs && f.profile_refs.length) {
    out.push(new Paragraph({
      children: [
        new TextRun({ text: 'Profile basis: ', bold: true }),
        new TextRun(f.profile_refs.join(', ')),
      ],
    }));
  }
  if (opts.unanchored) {
    out.push(new Paragraph({
      children: [new TextRun({ text: '⚠ Not placed in the document — manual review needed.', bold: true, italics: true })],
    }));
  }
  out.push(new Paragraph({ children: [new TextRun('')] }));
  return out;
}
