-- 0029_workspace_compare_finalize.sql
--
-- Compare runs can now be FINALIZED into a redline deliverable: a
-- tracked-changes .docx (when the proposed doc was a DOCX) or an
-- inline-redlined .pdf (when the proposed doc was a PDF). Plus an
-- always-generated markdown summary memo for the negotiation cover
-- email.
--
-- Adds two columns to the existing workspace_compare_runs table:
--   - finalized_format : 'docx' | 'pdf' — set by the finalize background
--                         worker so the UI knows what extension to
--                         download. workspace_compare_runs already has
--                         finalized_version_id (added in 0023) — we
--                         just need to know the format to render the
--                         right download button.
--   - summary_md       : the markdown summary memo. Generated by the
--                         finalize worker as a single LLM call against
--                         the user's decisions + per-diff rationales.
--                         Stored on the run row (not as a document
--                         version) since it's run-scoped, not document-
--                         scoped, and small (~2-4KB).
--
-- Also widens the run status check constraint to include 'finalizing'
-- so the UI can show "preparing redline…" while the background job
-- runs (~10-30s for DOCX, ~30-90s for PDF via the Modal service).
--
-- Safe to re-run.

alter table public.workspace_compare_runs
  add column if not exists finalized_format text
    check (finalized_format is null or finalized_format in ('docx','pdf')),
  add column if not exists summary_md text;

-- Widen status check. The existing constraint allows
-- pending/running/complete/partial/error; add 'finalizing' for the
-- brief window between user clicking Download Redline and the
-- finalized version landing.
alter table public.workspace_compare_runs
  drop constraint if exists workspace_compare_runs_status_check;

alter table public.workspace_compare_runs
  add constraint workspace_compare_runs_status_check
  check (status in ('pending','running','complete','partial','error','finalizing'));

comment on column public.workspace_compare_runs.finalized_format is
  '(0029) docx | pdf — format of the finalized redline output. Set when finalized_version_id is populated. UI dispatches the download button URL/extension off this.';
comment on column public.workspace_compare_runs.summary_md is
  '(0029) Always-generated markdown summary of the negotiation: who pushed back where, what was accepted, the key rationales. Run-scoped, not version-scoped. Used as the cover-email body when sending the redline back.';
